# Generated by Django 3.2.5 on 2021-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flixer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
