# Generated by Django 3.2.5 on 2021-07-23 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Flixer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
