# Generated by Django 3.2.5 on 2021-08-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flixer', '0002_usermovie_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
