# Generated by Django 3.2.5 on 2021-07-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flixer', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
