# Generated by Django 3.2.5 on 2021-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flixer', '0005_auto_20210728_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_value',
            field=models.CharField(max_length=1),
        ),
    ]
