# Generated by Django 3.2.5 on 2021-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flixer', '0006_alter_rating_rating_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=30)),
            ],
        ),
    ]
