# Generated by Django 3.2.5 on 2021-07-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flixer', '0008_alter_category_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Flixer.category'),
            preserve_default=False,
        ),
    ]
